/* 
  定义菜单列表每个菜单
*/
const menus = [
  {
    title:'home',
    Icon:'home',
    path:'/'
  },
  {
    title:'products',
    Icon:'appstore',
    path:'/products',
    children:[
      {
        title:'category',
        Icon:'bars',
        path:'/category'
      },
      {
        title:'product',
        Icon:'tool',
        path:'/product'
      }
    ]
  },
  {
    title:'user',
    Icon:'user',
    path:'/user'
  },
  {
    title:'role',
    Icon:'safety',
    path:'/role'
  },
  {
    title:'charts',
    Icon:'area-chart',
    path:'/charts',
    children:[
      {
        title:'bar',
        Icon:'bar-chart',
        path:'/charts/bar'
      },
      {
        title:'pie',
        Icon:'pie-chart',
        path:'/charts/pie'
      },
      {
        title:'line',
        Icon:'line-chart',
        path:'/charts/line'
      }
    ]
  }
]
//暴露出去
export default menus;