

const menus = [

  {
    title:'home',
    icon:'home',
    key:1,
    path:"/"
  },
  {
    title:'products',
    icon:'qrcode',
    key:2,
    path:'/products',
    children:[
      {
        title:'category',
        icon:'unordered-list',
        key:3,
        path:'/category'
      },
      {
        title:'product',
        icon:'tool',
        key:4,
        path:'/product'
      }
    ]
  },
  {
    title:'user',
    icon:'user',
    key:5,
    path:'/user'
  },
  {
    title:'role',
    icon:'safety',
    key:6,
    path:'/role'
  },
  {
    title:'charts',
    icon:'area-chart',
    key:7,
    path:'/charts',
    children:[
      {
        title:'bar',
        icon:'bar-chart',
        key:8,
        path:'/charts/bar'
      },
      {
        title:'pie',
        icon:'pie-chart',
        key:9,
        path:'/charts/pie'
      },
      {
        title:'line',
        icon:'line-chart',
        key:10,
        path:'/charts/line'
      }
    ]
  }
]
export default menus;